gitConstraints:
    expectedOriginHost: "gitlab.example.com"
jira:
    url: "https://jira.example.com"
    username: "username"
    password: "password"
gitlab:
    url: "https://gitlab.example.com"
    token: "token"
